server:
  port: 8080

spring:
  application:
    name: spring-data-with-liquibase-in-action
  liquibase:
    change-log: classpath:master-changelog.yml
    default-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
